name: Build ICS (Knihovna Vrdy)

on:
  schedule:
    - cron: "5 5 * * *"   # 05:05 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate ICS
        run: |
          mkdir -p docs
          python vrdy_knihovna_to_ics.py --out docs/vrdy_knihovna.ics

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update ICS ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)" || echo "Nothing to commit."
          git push
